

source 'https://cdn.cocoapods.org'
install! 'cocoapods', :deterministic_uuids => false
inhibit_all_warnings!

platform :ios, '11.0'

def shared_pods
  use_modular_headers!
  # pod 'XKKeychain', '~>1.0'
  # pod 'box-ios-sdk-v2', :git => 'https://github.com/fkuehne/box-ios-sdk-v2.git', :commit => '08161e74' #has a our fixes
  # pod 'CocoaHTTPServer', :git => 'https://github.com/fkuehne/CocoaHTTPServer.git' # has our fixes
  # pod 'xmlrpc', :git => 'https://github.com/fkuehne/xmlrpc.git', :commit => '3f8ce3a8' #fix case-sensitive FS
  # pod 'AFNetworking', '~>4.0'

  # debug
  # pod 'SwiftLint', '~> 0.47.1', :configurations => ['Debug']
end


target 'SPlayer' do
  
  pod 'ZFPlayer', '~> 4.1.4'
  pod 'ZFPlayer/ControlView', '~> 4.1.4'
  # 使用 ijkPlayer 支持的格式多
  pod 'ZFPlayer/ijkplayer', '~> 4.1.4'
  
  pod 'ZFPlayer/AVPlayer', '~> 4.1.4'
  
  pod 'Shimmer', '~> 1.0.2'
  pod 'AFNetworking', '~> 4.0.1'
  pod 'YYCache', '~> 1.0.4'
  pod 'SDWebImage', '~> 5.12.2'
  pod 'SDWebImageWebPCoder'
  pod 'Masonry'
  pod 'LMJHorizontalScrollText'
  pod 'MJRefresh', '~> 3.7.5'
      
  pod 'FMDB', '~> 2.7.5'
      
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMAPM'
  
  # 下载文件
#  pod 'MZDownloadManager', '~> 3.6'
  
  # 浏览器需求
  pod 'AXNavigationBackItemInjection'
  pod 'NJKWebViewProgress'
  pod 'Aspects'
  pod 'AXPracticalHUD'

  # VLC
  shared_pods
#  pod 'OBSlider', '1.1.0'
#  pod 'InAppSettingsKit', :git => 'https://github.com/Mikanbu/InAppSettingsKit.git', :commit => 'a429840' #tvOS fix
#  pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
#  pod 'GoogleSignIn', '6.2.0'
#  pod 'MobileVLCKit', '3.4.1b13'
#  pod 'VLCMediaLibraryKit', '0.11.0b2'
#  pod 'GTMAppAuth', '~> 1.0'
#  pod 'ADAL', :git => 'https://code.videolan.org/fkuehne/azure-activedirectory-library-for-objc.git', :commit => '348e94df'
#  pod 'MarqueeLabel', '4.0.2'
#  pod 'ObjectiveDropboxOfficial'
  
 #//pod <友盟+SDK名> 按需复制相应SDK名称代码

 #￥//依赖库

  
#  pod 'Google-Mobile-Ads-SDK'
  
#  pod 'MJRefresh', '~> 3.7.5'

end
